version: "3.8"

services:
  postgres:
    image: postgres:16.1
    volumes:
      - todo-postgres-data:/var/lib/psql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: todo-app
      POSTGRES_USER: fdmdev
    ports:
      - 2345:5432
    networks:
      - todo-app
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@fdmgroup.com"
      PGADMIN_DEFAULT_PASSWORD: "abc1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "8080:80"
    networks:
      - todo-app
    restart: unless-stopped
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 8088:8088
    volumes:
      - ./backend:/usr/app
    environment:
      DB_HOST: postgres
      DB_NAME: todo-app
      DB_USER: fdmdev
      DB_PORT: 5432
    working_dir: /usr/app
    networks:
      - todo-app
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - todo-app
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  todo-postgres-data:

networks:
  todo-app:
