#!/bin/bash
set -e

# Navigate to frontend directory
cd frontend

# Install dependencies in frontend directory
npm i

# Navigate to backend directory
cd ../backend

# Install dependencies in backend directory
npm i

# Start container and run in the background
docker compose up -d

# Open application on port 3000
open http://localhost:3000